# Generated by Django 4.0.3 on 2022-04-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='city',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='detail',
            name='country',
            field=models.IntegerField(default=1),
        ),
    ]
